development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  database: "bugtracker_developmentt"
  host: localhost
  port: 5433

test: 
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  database: "bugtracker_test"
  host: localhost
  port: 5433



production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  database: "bugtracker_production"
  host: localhost
  port: 5433
  
